# Generated by Django 2.2 on 2019-05-26 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji', models.CharField(max_length=1)),
                ('jlpt_level', models.CharField(choices=[('N5', 'N5'), ('N4', 'N4'), ('N3', 'N3'), ('N2', 'N2'), ('N1', 'N1')], max_length=2)),
                ('onyomi', models.CharField(blank=True, max_length=255)),
                ('kunyomi', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('meanings', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'kanji',
                'verbose_name_plural': 'kanji',
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yomi_type', models.CharField(choices=[('KU', 'Kun')], max_length=2)),
                ('reading', models.CharField(max_length=255)),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanjireading.Kanji')),
            ],
        ),
    ]
