# Generated by Django 2.2 on 2019-06-11 12:14

from django.db import migrations, models
import django.db.models.deletion

# Migration scripts
def create_readings_from_kanjiyomi(apps, schema_editor):
    Kanji = apps.get_model('kanjireading', 'Kanji')
    Reading = apps.get_model('kanjireading', 'Reading')
    KanjiReading = apps.get_model('kanjireading', 'KanjiReading')

    def create_reading(kanji, reading, yomi_type):
        new_reading = Reading.objects.create(pronounciation=reading)
        new_reading.save()

        kanjireading_object = KanjiReading.objects.create(kanji=kanji, reading=new_reading, yomi_type=yomi_type)
        kanjireading_object.save()

    for character in Kanji.objects.all():
        if character.onyomi:
            create_reading(character, character.onyomi, 'ON')

        if character.kunyomi:
            create_reading(character, character.kunyomi, 'KU')


# Migration proper
class Migration(migrations.Migration):

    dependencies = [
        ('kanjireading', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reading',
            old_name='reading',
            new_name='pronounciation',
        ),
        migrations.CreateModel(
            name='KanjiReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yomi_type', models.CharField(choices=[('KU', 'Kunyomi'),('ON', 'Onyomi')], max_length=2)),
                ('kanji', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kanji_readings', to='kanjireading.Kanji')),
                ('reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kanji_list', to='kanjireading.Reading')),
            ],
            options={
                'verbose_name': 'KanjiReading',
                'verbose_name_plural': 'KanjiReadings',
            },
        ),
        migrations.AddField(
            model_name='kanji',
            name='readings',
            field=models.ManyToManyField(related_name='kanji', through='kanjireading.KanjiReading', to='kanjireading.Reading'),
        ),
        migrations.RemoveField(
            model_name='reading',
            name='kanji',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='yomi_type',
        ),
        # Change current yomi to kanjireading here
        migrations.RunPython(create_readings_from_kanjiyomi),
        migrations.RemoveField(
            model_name='kanji',
            name='kunyomi',
        ),
        migrations.RemoveField(
            model_name='kanji',
            name='onyomi',
        ),
    ]
