# Generated by Django 2.2 on 2019-06-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanjireading', '0002_auto_20190611_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanji',
            name='kanji',
            field=models.CharField(max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='pronounciation',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
