# Generated by Django 2.2 on 2019-06-15 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanjireading', '0003_auto_20190616_0050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kanji',
            old_name='kanji',
            new_name='character',
        ),
    ]
